<a href="https://colab.research.google.com/github/sirius70/NLP_HW1/blob/main/token_counts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Empirical Regularities of Language

In this first homework assignment, you will familiarize yourself with some empirical regularities of natural language, Shannon entropy and Zipf's Law.

Read through this Jupyter notebook and fill in the parts marked with `TODO`. When you're ready to submit, print the notebook as a PDF and upload to Gradescope.

## Shannon Entropy

Shannon borrowed the concept of entropy from statistical physics to develop _information theory_, focused on encoding and compressing messages. A few years later, in 1950, he applied information theory to analyze human predictive ability—in other words, the entropy of the human language model. You can read the original article, [Prediction and Entropy of Printed English](https://languagelog.ldc.upenn.edu/myl/Shannon1950.pdf), for more details.

Your first task is to collect data on how predictable different letters are in an English sentence, depending on how much context in a word or sentence you have.

Go to the [Shannon game page](https://www.ccs.neu.edu/home/dasmith/courses/cs6120/shannon/) that we demonstrated in class. We already guessed part of Text 1, so work through Texts 2, 3, and 4.

In [ ]:
# TODO: Enter the arrays of numbers of guesses for Texts 2, 3, and 4 here.
text2_guesses = [13, 6,	5, 3, 1, 1, 1, 1, 9, 2, 2, 1, 1, 2, 1, 1, 2, 1, 11, 3, 4, 2, 1, 1, 1, 1, 1, 8, 4, 3, 2, 1, 10, 1, 1, 1, 1, 6, 5, 5, 1, 1, 1, 1, 1, 1, 1, 0]

text3_guesses = [1, 3, 1, 9, 5,	2, 1, 1, 8, 3, 1, 1, 1,	1, 1, 1, 1, 1, 1, 1, 3,	1, 1, 1, 1, 16, 2, 11, 1, 1, 1, 1, 1, 1, 1, 7, 2, 2, 1, 1, 1, 7, 4, 1, 5, 4, 7, 1, 4, 1, 1, 1, 3, 2, 1, 5, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 0]

text4_guesses = [2, 1, 5, 1, 1,	8, 3, 2, 2, 3, 1, 1, 1,	1, 1, 7, 4, 3, 1, 1, 1,	1, 1, 1, 1, 1, 2, 3, 1, 1, 7, 1, 13, 5, 5, 1, 1, 1, 1, 18, 2, 5, 1, 2, 5, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 1, 1, 0]

print(len(text2_guesses))


48


Rearrange the guess data into a two-dimensional array, relating number of characters of context (0, 1, 2, ...) to number of guesses required.

In other words, you might look in cell (2, 1) and read "2" if the number of times it took one guess to get the right letter with two characters of context was 2.

In [ ]:
# TODO: Create array of counts of guesses. Print out the array so we can see it.
import numpy as np

def build_table(guesses):
    guesses = [g for g in guesses if g > 0]
    max_context = len(guesses)
    max_guess = max(guesses)
    table = np.zeros((max_context, max_guess+1), dtype=int)
    for context, guess in enumerate(guesses):
        table[context, guess] += 1
    return table

text2_table = build_table(text2_guesses)
text3_table = build_table(text3_guesses)
text4_table = build_table(text4_guesses)

np.set_printoptions(threshold=np.inf)

print("Text2 table:\n", text2_table)
print("\nText3 table:\n", text3_table)
print("\nText4 table:\n", text4_table)


Text2 table:
 [[0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0

Now you can compute Shannon's upper and lower bounds on the entropy of your predictive distribution for English. The upper bound, as a function of the number of context characters $N$, is just the Shannon entropy of the distribution of numbers of guesses. In other words, it's the entropy of the original text as &ldquo;reduced&rdquo; by the human encoder to a sequence of numbers of guesses.

$F_N = -\sum_{i=1}^{27} q_i^N \log_2 q_i^N$

where $q_i^N$ is the number of times you took $i$ guesses with $N$ characters of context, i.e., one of the cells in the table you computed. The number of guesses ranges from 1 to 27 since we restrict ourselves to 26 letters plus space. In computing entropy, we define $0 \log 0 = 0$.

In [ ]:
# TODO: Compute the upper bound for each amount of context N and print it out.

import numpy as np

# Provided data
text2_guesses = [13,6,5,3,1,1,1,1,9,2,2,1,1,2,1,1,2,1,11,3,4,2,1,1,1,1,1,8,4,3,2,1,10,1,1,1,1,6,5,5,1,1,1,1,1,1,1,0]
text3_guesses = [1,3,1,9,5,2,1,1,8,3,1,1,1,1,1,1,1,1,1,1,3,1,1,1,1,16,2,11,1,1,1,1,1,1,1,7,2,2,1,1,1,7,4,1,5,4,7,1,4,1,1,1,3,2,1,5,1,2,1,1,1,1,1,2,1,1,1,0]
text4_guesses = [2,1,5,1,1,8,3,2,2,3,1,1,1,1,1,7,4,3,1,1,1,1,1,1,1,1,2,3,1,1,7,1,13,5,5,1,1,1,1,18,2,5,1,2,5,1,1,1,1,1,1,1,1,4,1,1,1,0]

# Helper: remove only trailing zero if present
def clean_trailing_zero(lst):
    return lst[:-1] if lst and lst[-1] == 0 else lst

texts = [clean_trailing_zero(text2_guesses),
         clean_trailing_zero(text3_guesses),
         clean_trailing_zero(text4_guesses)]

MAX_G = 27  # guesses range 1..27 (26 letters + space)
max_N = max(len(t) for t in texts)

# Build count table q_{N,i} with rows N=0..max_N-1 and columns i=1..27 (index 0 unused)
counts = np.zeros((max_N, MAX_G + 1), dtype=int)
for t in texts:
    for ctx, g in enumerate(t):
        if 1 <= g <= MAX_G:
            counts[ctx, g] += 1

# Entropy function with 0*log2(0)=0 convention
def entropy_from_counts(row):
    total = row.sum()
    if total == 0:
        return None
    p = row / total
    nz = p > 0
    return float(-np.sum(p[nz] * np.log2(p[nz])))

np.set_printoptions(threshold=np.inf)

# Compute and print upper bound F_N for each N
print(f"{'N':>3} | {'total':>5} | {'F_N (bits)':>12}")
print("-" * 28)
for N in range(max_N):
    row = counts[N, 1:MAX_G+1]   # consider guesses 1..27
    total = int(row.sum())
    H = entropy_from_counts(row)
    h_str = f"{H:.6f}" if H is not None else "no data"
    print(f"{N:3d} | {total:5d} | {h_str:>12}")


  N | total |   F_N (bits)
----------------------------
  0 |     3 |     1.584963
  1 |     3 |     1.584963
  2 |     3 |     0.918296
  3 |     3 |     1.584963
  4 |     3 |     0.918296
  5 |     3 |     1.584963
  6 |     3 |     0.918296
  7 |     3 |     0.918296
  8 |     3 |     1.584963
  9 |     3 |     0.918296
 10 |     3 |     0.918296
 11 |     3 |    -0.000000
 12 |     3 |    -0.000000
 13 |     3 |     0.918296
 14 |     3 |    -0.000000
 15 |     3 |     0.918296
 16 |     3 |     1.584963
 17 |     3 |     0.918296
 18 |     3 |     0.918296
 19 |     3 |     0.918296
 20 |     3 |     1.584963
 21 |     3 |     0.918296
 22 |     3 |    -0.000000
 23 |     3 |    -0.000000
 24 |     3 |    -0.000000
 25 |     3 |     0.918296
 26 |     3 |     0.918296
 27 |     3 |     1.584963
 28 |     3 |     0.918296
 29 |     3 |     0.918296
 30 |     3 |     1.584963
 31 |     3 |    -0.000000
 32 |     3 |     1.584963
 33 |     3 |     0.918296
 34 |     3 |     0.918296

Shannon derived a lower bound on entropy from the guess data as

$\sum_{i=1}^{27} i(q_i^N - q_{i+1}^N) \log_2 i$

In [ ]:
# TODO: Compute thew lower bound for each amount of context N and print it out.

## Zipf's Law

Now let's look at some text data directly to see the skewed distribution of tokens predicted by Zipf's Law. Recall that Zipf's law states that a word's rank (from the most common word at rank 1 on down) to its frequency is approximately a constant, i.e., $r \cdot f = k$. Equivalently, we can divide both sides by the total number of tokens $N$ to get $r \cdot P_r = c$, where $c = k/N$ and $P_r = f/N$ is the _relative frequency_ of word $r$.

We start by downloading a sample of 1000 open-access English books from [Project Gutenberg](https://gutenberg.org/).

In [13]:
# If your local environment doesn't have the wget command,
# you can comment this out and download it manually.
!wget "http://khoury.northeastern.edu/home/dasmith/pg-sample.json.gz"

--2025-09-18 03:06:32--  http://khoury.northeastern.edu/home/dasmith/pg-sample.json.gz
Resolving khoury.northeastern.edu (khoury.northeastern.edu)... 52.70.229.197
Connecting to khoury.northeastern.edu (khoury.northeastern.edu)|52.70.229.197|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 150984197 (144M) [application/x-gzip]
Saving to: ‘pg-sample.json.gz.1’

pg-sample.json.gz.1 100%[===================>] 143.99M   134MB/s    in 1.1s    

2025-09-18 03:06:33 (134 MB/s) - ‘pg-sample.json.gz.1’ saved [150984197/150984197]



The file is compressed with gzip and is in a JSON lines format. Each line is one JSON record, which we parse with the `json` library.

Here we print out the keys in the first record: `id`, `author`, `title`, and `text`.

In [12]:
import gzip, json
for line in gzip.open("pg-sample.json.gz", mode="rt", encoding="utf-8"):
  rec = json.loads(line)
  print(rec.keys())
  print(rec['author'])
  print(rec['title'])
  print(rec['text'][0:100])
  break

dict_keys(['id', 'author', 'title', 'text'])
Jefferson, Thomas
The Declaration of Independence of the United States of America


This is a retranscription of one of the first Project
Gutenberg Etexts, offically dated December 3


Your task now is to **tokenize** the text in the `text` field of each record into an array of words. Later on in this course, we will discuss learning better tokenizers. For now, you should separate words on whitespace (space, newline, tab) and punctuation. Convert the tokens to lower case, and keep only those tokens that have at least one letter a-z in them. In general, numerals in text tend not to follow Zipf's law but [Benford's law](https://en.wikipedia.org/wiki/Benford%27s_law).

You might use _regular expressions_ (e.g., the `re.split` function) to help with tokenization and filtering.

After you have tokenized, compute $N$, the total number of tokens in the corpus and print it out.

In [25]:
# TODO: Compute an array of tokens in the corpus
# Compute the total number of tokens N and print it out.

import gzip
import json
import re

all_tokens = []

with gzip.open("pg-sample.json.gz", mode="rt", encoding="utf-8") as f:
    for line in f:
        rec = json.loads(line)
        text = rec['text']

        # Split into tokens
        tokens = re.split(r'[\s\W_]+', text)

        # Convert to lowercase and keep only tokens with at least one letter
        tokens = [t.lower() for t in tokens if re.search(r'[a-z]', t)]

        all_tokens.extend(tokens)

N = len(all_tokens)

print("Total tokens in corpus:", N)


Total tokens in corpus: 68003466


Now, count the frequency each unigram (distinct word) in the corpus and sort them in an array in descending order of frequency. The first item in your array should be the most common word. Print out that word and its frequency

In [26]:
# TODO: Compute an arrary of unigrams in descending order of frequency.
# Print the most common word and its frequency.

from collections import Counter

# Count frequencies of each unigram
unigram_counts = Counter(all_tokens)
print(len(all_tokens))

# Sort unigrams in descending order of frequency
sorted_unigrams = unigram_counts.most_common()

# Get the most common word and its frequency
most_common_word, most_common_freq = sorted_unigrams[0]

print("Most common word:", most_common_word)
print("Frequency:", most_common_freq)


68003466
Most common word: the
Frequency: 4440562


Now, you can look at the Zipf's law relationship between rank and relative frequency (i.e., frequency divided by $N$). Plot the data using a python graphing package such as matplotlib, plotly, or plotnine. This doesn't have to be a fancy graph, so use whatever you're familiar with. Both axes should be on a log scale. If your package doesn't support log scales, you can take the log of the rank and relative frequency yourself before plotting. Recall that since python arrays are zero-indexed, the rank 1 word will be element 0 of your sorted array.

In [ ]:
# TODO: Plot rank vs. relative frequency of unigrams.

Now, take your array of tokens and compute the counts of both the bigrams and trigrams and sort them in descending order of frequency. Print out the most common bigram and trigram.

In [ ]:
# TODO: Compute sorted bigram and trigram statistics.
# Print out the most common bigram and trigram.
# Plot rank vs. relative frequency for bigrams and trigrams.
# You may make separate plots or put them on the same plot and label them.

**TODO**: Finally, write your visual impressions of the fit of the unigram, bigram, and trigram distributions. This doesn't need to be statistically rigorous.